### ISSUE TITLE
Minor changes for Python 3.x compatibility

### ISSUE THREAD

**Issue by esvhd** [vinhkhuc/PyTorch-Mini-Tutorials#3]
Hi there,

Thanks for sharing this great set of tutorials. I made a few tiny changes to make it work for Python 3.x. Would you be interested in a pull request? 

Changes:
1. use integer division for calculating minibatch size
2. use `urllib.reqeust.urlretrieve()` if python major version is > 2
3. download MNIST files if any of the data files is missing, instead of just checking folder existence.

Thanks.

**Comment by vinhkhuc** [comment]
Just merged. Thanks!
